[advisories]
unmaintained = "deny"
yanked = "deny"
notice = "deny"
unsound = "deny"
ignore = ["RUSTSEC-2022-0048"]

[licenses]
allow-osi-fsf-free = "either"

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = [
  { name = "syn", version = "1.0" },
  { name = "ahash", version = "0.7.6" },
  { name = "redox_syscall", version = "0.2" },
  { name = "regex-syntax", version = "0.6" },
  { name = "windows_x86_64_msvc", version = "0.42" },
  { name = "windows_x86_64_gnullvm", version = "0.42" },
  { name = "windows_x86_64_gnu", version = "0.42" },
  { name = "windows_i686_msvc", version = "0.42" },
  { name = "windows_i686_gnu", version = "0.42" },
  { name = "windows_aarch64_msvc", version = "0.42" },
  { name = "windows_aarch64_gnullvm", version = "0.42" },
  { name = "windows-targets", version = "0.42" },
  { name = "windows-sys", version = "0.45" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
